### ISSUE TITLE
Missing tutorials

### ISSUE THREAD

**Issue by Zumbalamambo** [slidenerd/vue-list-detail-nested-route#2]
Learned Android app dev from you during 2015 through Youtube. Got into Development. Building apps for the past 5 years. Miss your online presence.  It would be great to see great contents especially on newer technologies like Flutter. thank you Mentor

**Comment by slidenerd** [comment]
Been working on products for a while so dont get much time to do tutorials, i am however planning to start a different channel with the same format with several instructors following the format covering Flutter Vue Docker etc

**Comment by Zumbalamambo** [comment]
Looking forward to seeing you soon champ.. Don't forget to update the years old fans of your channel like me the name of your new channel
